export const langParams = {
    ru: [
        'Квиз по художникам',
        'Квиз по картинам',
        'НАСТРОЙКИ',
        'ЯЗЫК РУС / АНГЛ',
        'ГРОМКОСТЬ',
        'ИГРА НА ВРЕМЯ',
        'ВРЕМЯ НА ВОПРОС',
        'сек',
        'СОХРАНИТЬ',
        'Разработчик: Руслан Вильданов',
        'Категории',
        'РАУНД',
        'ДОМОЙ',
        'Кто автор этой картины?',
        'Какую из этих картин написал ',
        'Вы уверены, что хотите завершить тест',
        'Да',
        'Отмена',
        'Результаты',
        'Назад к категориям',
        'Тип игры: угадать художника по картине',
        'Тип игры: угадать картину по имени её автора',
    ],
    en: [
        'ARTIST QUIZ',
        'PICTURES QUIZ',
        'SETTINGS',
        'LANGUAGE RU / EN',
        'VOLUME',
        'TIMER GAME',
        'TIME TO ANSWER',
        'sec',
        'SAVE',
        'Developer: Ruslan Vildanov',
        'CATEGORIES',
        'ROUND',
        'HOME',
        'Who is the author of this picture?',
        'Which of these paintings did paint',
        'Are you sure you want to complete the test?',
        'Yes',
        'Cancel',
        'SCORE',
        'Back to categories',
        'Type of game: to guess the artist by the picture',
        'Type of game: to guess the picture by the name of its author',
    ],
};
