export const langParams = {
    ru: {
        artistQuiz: 'Квиз по художникам',
        picturesQuiz: 'Квиз по картинам',
        settings: 'НАСТРОЙКИ',
        shangeLang: 'ЯЗЫК РУС / АНГЛ',
        sound: 'ГРОМКОСТЬ',
        gameTime: 'ИГРА НА ВРЕМЯ',
        timeForQuestion: 'ВРЕМЯ НА ВОПРОС',
        second: 'сек',
        save: 'СОХРАНИТЬ',
        developer: 'Разработчик: Руслан Вильданов',
        categories: 'Категории',
        round: 'РАУНД',
        home: 'ДОМОЙ',
        whoAuthor: 'Кто автор этой картины?',
        whichPicture: 'Какую из этих картин написал ',
        questionCancelGame: 'Вы уверены, что хотите завершить тест',
        agree: 'Да',
        cancel: 'Отмена',
        results: 'Результаты',
        backToCategories: 'Назад к категориям',
        quizType: 'Тип игры: угадать художника по картине',
        pictureType: 'Тип игры: угадать картину по имени её автора',
        artist: 'Художники',
        quiz: '',
        pictures: 'Картины',
    },
    en: {
        artistQuiz: 'ARTIST QUIZ',
        picturesQuiz: 'PICTURES QUIZ',
        settings: 'SETTINGS',
        shangeLang: 'LANGUAGE RU / EN',
        sound: 'VOLUME',
        gameTime: 'TIMER GAME',
        timeForQuestion: 'TIME TO ANSWER',
        second: 'sec',
        save: 'SAVE',
        developer: 'Developer: Ruslan Vildanov',
        categories: 'CATEGORIES',
        round: 'ROUND',
        home: 'HOME',
        whoAuthor: 'Who is the author of this picture?',
        whichPicture: 'Which of these paintings did paint',
        questionCancelGame: 'Are you sure you want to complete the test?',
        agree: 'Yes',
        cancel: 'Cancel',
        results: 'SCORE',
        backToCategories: 'Back to categories',
        quizType: 'Type of game: to guess the artist by the picture',
        pictureType: 'Type of game: to guess the picture by the name of its author',
        artist: 'ARTIST ',
        quiz: 'QUIZ',
        pictures: 'PICTURES ',
    },
};
