import './style.scss';
import './js/settings';
import './js/blocksHide';
import './js/quiz';
import './js/score';
import './js/picturesQuiz';
import './js/changeLang';
import './js/sound';
import './js/commonFunctions';
